# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "254cac4fc6295b38a889f875fc8ee8e9"
name = "reel-vin-v2"
application_url = "https://shopify-reel-vin-v2.vercel.app"
embedded = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_locations,read_files,write_inventory,write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://shopify-reel-vin-v2.vercel.app/auth/callback" ]
